# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14D2b8oFZqnzdKAb34pK7CilTyRwPytmv
"""

1+1

x=1

type(x)

y=1.1

type(y)

z=True

type(z)